version: '3'

volumes:
  prometheus_data:
    name: prometheus_data
    driver: local

  grafana_data:
    name: grafana_data
    driver: local

# networks:
#   monitoring:
#     external: true

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - './config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - 'prometheus_data:/prometheus'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  snmp:
    container_name: snmp-exporter
    image: prom/snmp-exporter
    restart: always
    volumes:
      - ./snmp/:/etc/snmp_exporter/
    ports:
      - "9116:9116"
    depends_on:
      - prometheus

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:8.0.0
    restart: unless-stopped
    volumes:
      - 'grafana_data:/var/lib/grafana'
      - './config/grafana:/etc/grafana/provisioning/datasources'
    ports:
      - 3000:3000
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081