global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: "Mikrotik"

    # Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    scrape_timeout: 10s
    tls_config:
      insecure_skip_verify: true

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "mikrotik"
    static_configs:
      - targets:
          - 172.16.0.1 # SNMP Device 1
          - 10.0.0.1 # SNMP Remote 1
    metrics_path: /snmp
    params:
      module: [mikrotik]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116 # The SNMP exporter's real hostname:port.
